name: "lamp-stack"

services:
  apache-httpd:
    build:
      context: .
      dockerfile: ./containers/httpd/Dockerfile
    volumes:
      - ./app/website:/var/www/html
    ports:
      - 80:80/tcp
    depends_on:
      - php-fpm
      - mariadb
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./containers/php-fpm/Dockerfile
    volumes:
      - ./app/website:/var/www/html
    links:
      - mariadb

  mariadb:
    build:
      context: .
      dockerfile: ./containers/mariadb/Dockerfile
    ports:
      - 3306:3306/tcp
    volumes:
      - ./app/database:/var/lib/mysql
